/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlers.BicycleRental.*;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author francisco Carena
 */


public class MainWindow extends javax.swing.JFrame {
    
    private static final Logger log = LoggerFactory.getLogger(MainWindow.class);

    public static String getMessage(String resource, String word){
         return ResourceBundle.getBundle(resource,Locale.getDefault()).getString(word);        
    }
    
    /**
     * Creates new form HotelJFrame
     */
    private static final SpringConfig springConfig = new SpringConfig();
    private static final BicycleManager bicycleManager = new BicycleManagerImpl(springConfig.dataSource());
    private static final CustomerManager customerManager = new CustomerManagerImpl(springConfig.dataSource());
    private static final RentalManager rentalManager = new RentalManagerImpl(springConfig.dataSource());
    private final BicycleTableModel bicycleTableModel;
    private final CustomerTableModel customerTableModel;
    private final RentalTableModel rentalTableModel;
    
    /**
     * getBicycleTableModel
     *
     * @return Table model for guest table
     */
    public BicycleTableModel getBicycleTableModel() {
        log.debug("MainWindow.getBTM");
        return bicycleTableModel;
    }
    public CustomerTableModel getCustomerTableModel() {
        log.debug("MainWindow.getCTM");
        return customerTableModel;
    }
    public RentalTableModel getRentalTableModel() {
        log.debug("MainWindow.getRTM");
        return rentalTableModel;
    }

    public static BicycleManager getBicycleManager() {
        log.debug("MainWindow.getBM");
        return bicycleManager;
    }
    public static CustomerManager getCustomerManager() {
        log.debug("MainWindow.getCM");
        return customerManager;
    }
    public static RentalManager getRentalManager() {
        log.debug("MainWindow.getRM");
        return rentalManager;
    }

    public JTable getBicycleTable() {
        log.debug("MainWindow.getBT");
        return bicycleTable;
    }
    public JTable getCustomerTable(){
        log.debug("MainWindow.getCT");
        return customerTable;
    }
    public JTable getRentalTable(){
        log.debug("MainWindow.getRT");
        return rentalTable;
    }
    
    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {
        log.debug("Mainwindow ctor");
        this.bicycleTableModel = new BicycleTableModel();
        this.customerTableModel = new CustomerTableModel();
        this.rentalTableModel = new RentalTableModel();
        this.rentalTableModel.reload();
        this.customerTableModel.reload();
        this.bicycleTableModel.reload();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        customerPanel = new javax.swing.JPanel();
        customerScrollPane = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        cAddButton = new javax.swing.JButton();
        cEditButton = new javax.swing.JButton();
        cDeleteButton = new javax.swing.JButton();
        rentalsPanel = new javax.swing.JPanel();
        rEditButton = new javax.swing.JButton();
        rDeleteButton = new javax.swing.JButton();
        rCreateButton = new javax.swing.JButton();
        rentalScrollPane = new javax.swing.JScrollPane();
        rentalTable = new javax.swing.JTable();
        bicyclePanel = new javax.swing.JPanel();
        bicycleScrollPane = new javax.swing.JScrollPane();
        bicycleTable = new javax.swing.JTable();
        bAddButton = new javax.swing.JButton();
        bEditButton = new javax.swing.JButton();
        bDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerTable.setModel(this.customerTableModel);
        customerTable.getTableHeader().setReorderingAllowed(false);
        customerScrollPane.setViewportView(customerTable);

        cAddButton.setText(MainWindow.getMessage("texts","Main_cAdd"));
        cAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAddButtonActionPerformed(evt);
            }
        });

        cEditButton.setText(MainWindow.getMessage("texts","Main_cEdit"));
        cEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEditButtonActionPerformed(evt);
            }
        });

        cDeleteButton.setText(MainWindow.getMessage("texts","Main_cDelete"));
        cDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addComponent(customerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cEditButton)
                    .addComponent(cAddButton)
                    .addComponent(cDeleteButton))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addComponent(customerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cAddButton)
                .addGap(18, 18, 18)
                .addComponent(cEditButton)
                .addGap(18, 18, 18)
                .addComponent(cDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("texts"); // NOI18N
        jTabbedPane2.addTab(bundle.getString("Main_cTab"), customerPanel); // NOI18N

        rEditButton.setText(MainWindow.getMessage("texts","Main_rEdit"));
        rEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEditButtonActionPerformed(evt);
            }
        });

        rDeleteButton.setText(MainWindow.getMessage("texts","Main_rDelete"));
        rDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDeleteButtonActionPerformed(evt);
            }
        });

        rCreateButton.setText(MainWindow.getMessage("texts", "Main_rAdd"));
        rCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCreateButtonActionPerformed(evt);
            }
        });

        rentalTable.setModel(this.rentalTableModel);
        rentalTable.getTableHeader().setReorderingAllowed(false);
        rentalScrollPane.setViewportView(rentalTable);

        javax.swing.GroupLayout rentalsPanelLayout = new javax.swing.GroupLayout(rentalsPanel);
        rentalsPanel.setLayout(rentalsPanelLayout);
        rentalsPanelLayout.setHorizontalGroup(
            rentalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalsPanelLayout.createSequentialGroup()
                .addComponent(rentalScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rentalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rEditButton)
                    .addComponent(rCreateButton)
                    .addComponent(rDeleteButton))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        rentalsPanelLayout.setVerticalGroup(
            rentalsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rCreateButton)
                .addGap(18, 18, 18)
                .addComponent(rEditButton)
                .addGap(18, 18, 18)
                .addComponent(rDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rentalsPanelLayout.createSequentialGroup()
                .addComponent(rentalScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(bundle.getString("Main_rTab"), rentalsPanel); // NOI18N

        bicycleTable.setModel(this.bicycleTableModel);
        bicycleTable.getTableHeader().setReorderingAllowed(false);
        bicycleScrollPane.setViewportView(bicycleTable);
        bicycleTable.getAccessibleContext().setAccessibleName("");

        bAddButton.setText(MainWindow.getMessage("texts", "Main_bAdd"));
        bAddButton.setAutoscrolls(true);
        bAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddButtonActionPerformed(evt);
            }
        });

        bEditButton.setText(MainWindow.getMessage("texts", "Main_bEdit"));
        bEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditButtonActionPerformed(evt);
            }
        });

        bDeleteButton.setText(MainWindow.getMessage("texts", "Main_bDelete"));
        bDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bicyclePanelLayout = new javax.swing.GroupLayout(bicyclePanel);
        bicyclePanel.setLayout(bicyclePanelLayout);
        bicyclePanelLayout.setHorizontalGroup(
            bicyclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bicyclePanelLayout.createSequentialGroup()
                .addComponent(bicycleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bicyclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDeleteButton)
                    .addComponent(bAddButton)
                    .addComponent(bEditButton))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        bicyclePanelLayout.setVerticalGroup(
            bicyclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bicyclePanelLayout.createSequentialGroup()
                .addComponent(bicycleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bicyclePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAddButton)
                .addGap(18, 18, 18)
                .addComponent(bEditButton)
                .addGap(18, 18, 18)
                .addComponent(bDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(bundle.getString("Main_bTab"), bicyclePanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAddButtonActionPerformed
        new CustomerAddPopUp(this,rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_cAddButtonActionPerformed

    private void cEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEditButtonActionPerformed
       try {
        new CustomerEditPopUp(this,rootPaneCheckingEnabled).setVisible(true);
       } catch (NullPointerException | IllegalArgumentException npe) {
           JOptionPane.showMessageDialog(rootPane, MainWindow.getMessage("texts", "ErrorNothingSelected"));
       }
    }//GEN-LAST:event_cEditButtonActionPerformed

    private void cDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDeleteButtonActionPerformed
        try {
        new CustomerDeletePopUp(this,rootPaneCheckingEnabled).setVisible(true);
        } catch (NullPointerException | IllegalArgumentException npe) {
          JOptionPane.showMessageDialog(rootPane, MainWindow.getMessage("texts", "ErrorNothingSelected"));
        }
        
    }//GEN-LAST:event_cDeleteButtonActionPerformed

    private void rCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCreateButtonActionPerformed
        new RentalAddPopUp(this,rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_rCreateButtonActionPerformed

    private void rDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDeleteButtonActionPerformed
        try {
        new RentalDeletePopUp(this,rootPaneCheckingEnabled).setVisible(true);
        } catch (NullPointerException | IllegalArgumentException npe) {
          JOptionPane.showMessageDialog(rootPane, MainWindow.getMessage("texts", "ErrorNothingSelected"));
        }
    }//GEN-LAST:event_rDeleteButtonActionPerformed

    private void rEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEditButtonActionPerformed
        try {
        new RentalEditPopUp(this,rootPaneCheckingEnabled).setVisible(true);
        } catch (NullPointerException | IllegalArgumentException npe) {
          JOptionPane.showMessageDialog(rootPane, MainWindow.getMessage("texts", "ErrorNothingSelected"));
        }
    }//GEN-LAST:event_rEditButtonActionPerformed

    private void bDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteButtonActionPerformed
        try {
        new BicycleDeletePopUp(this,rootPaneCheckingEnabled).setVisible(true);
        } catch (NullPointerException | IllegalArgumentException npe) {
          JOptionPane.showMessageDialog(rootPane, MainWindow.getMessage("texts", "ErrorNothingSelected"));
        }
    }//GEN-LAST:event_bDeleteButtonActionPerformed

    private void bEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditButtonActionPerformed
        try {
        new BicycleEditPopUp(this,rootPaneCheckingEnabled).setVisible(true);
        } catch (NullPointerException | IllegalArgumentException npe) {
          JOptionPane.showMessageDialog(rootPane, MainWindow.getMessage("texts", "ErrorNothingSelected"));
        }
    }//GEN-LAST:event_bEditButtonActionPerformed

    private void bAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddButtonActionPerformed
        new BicycleAddPopUp(this,rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_bAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                log.debug("MainWindow.run");
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddButton;
    private javax.swing.JButton bDeleteButton;
    private javax.swing.JButton bEditButton;
    private javax.swing.JPanel bicyclePanel;
    private javax.swing.JScrollPane bicycleScrollPane;
    private javax.swing.JTable bicycleTable;
    private javax.swing.JButton cAddButton;
    private javax.swing.JButton cDeleteButton;
    private javax.swing.JButton cEditButton;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JScrollPane customerScrollPane;
    private javax.swing.JTable customerTable;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton rCreateButton;
    private javax.swing.JButton rDeleteButton;
    private javax.swing.JButton rEditButton;
    private javax.swing.JScrollPane rentalScrollPane;
    private javax.swing.JTable rentalTable;
    private javax.swing.JPanel rentalsPanel;
    // End of variables declaration//GEN-END:variables
}
