/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlers.BicycleRental.Rental;
import Controlers.BicycleRental.RentalManager;
import Controlers.BicycleRental.ServiceFailureException;
import java.awt.event.WindowEvent;
import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Francisco Carena
 */
public class RentalDeletePopUp extends javax.swing.JDialog {
    private static final Logger log = LoggerFactory.getLogger(RentalDeletePopUp.class);
    private final Rental rental;
    private static final RentalManager rm = MainWindow.getRentalManager();
    private static RentalTableModel rtm;
    private final int selectedRow;
    
    private class RDeleteSW extends SwingWorker <Integer,Void> {
        private final Rental rental;
        
        public RDeleteSW(Rental r) {
            this.rental = r;
        }
        
        @Override
        protected Integer doInBackground() throws Exception {
            log.debug("RDeleteSW.doInBG");
            rm.deleteRental(rental);            
            return 0;
        }
        
        @Override
        protected void done(){
            log.debug("RDeleteSW.done");
            try{
                get();
                rtm.reload();
            }catch(ExecutionException exex){
                if(exex.getCause().getClass().equals(ServiceFailureException.class)){
                    log.debug("SFE:failed rental deletion");
                    JOptionPane.showMessageDialog(rootPane, MainWindow.getMessage("texts", "ErrorDeleteRental"));
                }
            }catch(InterruptedException iex){
                log.error("Done method deleting rental interrupted");
                throw new RuntimeException(MainWindow.getMessage("texts", "ErrorDeletingInterruptedRen"),iex);
            }
        }
    }
  
    
    /**
     * Creates new form RentalDeletePopUp
     */
    public RentalDeletePopUp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        log.debug("RentalDeletePopUp ctor");
        selectedRow = ((MainWindow) getParent()).getRentalTable().getSelectedRow();
        rtm = ((MainWindow)getParent()).getRentalTableModel();
        this.rental = rm.getRentalByID((Long)rtm.getValueAt(selectedRow,0));
        initComponents();
    }

    private void deleteRental(){
        log.debug("Deleting rental");
        RDeleteSW rdsw = new RDeleteSW(rental);
        rdsw.execute();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descriptionLabel = new javax.swing.JLabel();
        rentedFromLabel = new javax.swing.JLabel();
        rentedToLabel = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        bicycleLable = new javax.swing.JLabel();
        rentedFromLabel2 = new javax.swing.JLabel();
        rentedToLabel2 = new javax.swing.JLabel();
        customerLabel2 = new javax.swing.JLabel();
        bicycleLabel2 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        NOButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        descriptionLabel.setText(MainWindow.getMessage("texts","RDP_desc"));

        rentedFromLabel.setText(MainWindow.getMessage("texts", "RFrom"));

        rentedToLabel.setText(MainWindow.getMessage("texts", "RUntil"));

        customerLabel.setText(MainWindow.getMessage("texts", "RCustomer"));

        bicycleLable.setText(MainWindow.getMessage("texts","RBicycle"));

        rentedFromLabel2.setText(rental.getRentedFrom().toString());

        rentedToLabel2.setText(rental.getRentedFrom().toString());

        customerLabel2.setText(rental.getCustomer().toString());

        bicycleLabel2.setText(rental.getBicycle().toString());

        OKButton.setText(MainWindow.getMessage("texts", "Popup_OK"));
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        NOButton.setText(MainWindow.getMessage("texts", "Popup_NO"));
        NOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NOButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OKButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rentedFromLabel)
                                    .addComponent(rentedToLabel)
                                    .addComponent(bicycleLable))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bicycleLabel2)
                                    .addComponent(customerLabel2)
                                    .addComponent(rentedToLabel2)
                                    .addComponent(rentedFromLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(descriptionLabel)))
                        .addGap(37, 137, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(descriptionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentedFromLabel)
                    .addComponent(rentedFromLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentedToLabel)
                    .addComponent(rentedToLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerLabel)
                    .addComponent(customerLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bicycleLable)
                    .addComponent(bicycleLabel2))
                .addGap(28, 28, 28)
                .addComponent(NOButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(OKButton)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOButtonActionPerformed
        this.setVisible(false);
        this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_NOButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        deleteRental();
        rtm.reload();
        this.setVisible(false);
        this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_OKButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalDeletePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalDeletePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalDeletePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalDeletePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CustomerDeletePopUp dialog = new CustomerDeletePopUp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NOButton;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel bicycleLabel2;
    private javax.swing.JLabel bicycleLable;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customerLabel2;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel rentedFromLabel;
    private javax.swing.JLabel rentedFromLabel2;
    private javax.swing.JLabel rentedToLabel;
    private javax.swing.JLabel rentedToLabel2;
    // End of variables declaration//GEN-END:variables
}
